version: '3'

services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker-HRI-583
    privileged: true
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - 2376:2376

  myjenkins-blueocean:
    build:
      context: .
      dockerfile: Dockerfile
    image: myjenkins-blueocean:2.426.1-1
    container_name: jenkins-blueocean-HRI-583
    restart: on-failure
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - 5555:8080
      - 50000:50000

  keycloak:
    image: quay.io/keycloak/keycloak:13.0.0
    container_name: keycloak-HRI-583
    ports:
     - 8080:8080
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1-HRI-583
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
     memlock:
      soft: -1
      hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards-HRI-583
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - opensearch-net
  
  # coffee-machine:
  #   image: mcr.microsoft.com/dotnet/aspnet:7.0
  #   container_name: coffee-machine-HRI-583
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-coffee-machine
  #   environment:
  #     - ASPNETCORE_URLS=http://*:5110
  #     - ConnectionStrings__DefaultConnection=Server=172.26.192.1;Port=5432;Database=TestDBNew;User Id=postgres;Password=Vadim696;
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   expose:
  #     - "5110"
  #   ports:
  #     - "5110:5110"
  #   networks:
  #     - coffee-machine-net  

  coffee-machine: 
    build: 
      dockerfile: CoffeMachine/Dockerfile
    image: coffee-machine:latest 
    container_name: coffee-machine-HRI-583
    networks:
      - coffee-machine-net 
    ports: 
      - 5110:5110

  coffee-machine-tests:
    build:
      context: .
      dockerfile: CoffeeMachine.Tests/Dockerfile
    image: coffee-machine-tests:latest
    container_name: coffee-machine-tests-HRI-583
    networks:
      - coffee-machine-net

networks:
  jenkins:
  opensearch-net:
  coffee-machine-net:

volumes:
  jenkins-docker-certs:
  opensearch-data:
  jenkins-data:
  coffee-machine-data: